### ISSUE TITLE
Doesn't solve the registry variable substitution

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/env-exporter#1]
Consider I have the following:
![image](https://user-images.githubusercontent.com/92793/30707152-bcb491be-9f24-11e7-872f-fa0620687a5f.png)

`Export-Env` will still show it as `C:\Windows`. This setting will not round-trip properly. We need to fix that.

**Comment by beatcracker** [comment]
~~AFAIK the only way do this, is to read the registry directly~~. See how [Chocolatey](https://github.com/chocolatey/choco) handles this:

* [Update-SessionEnvironment.ps1](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Update-SessionEnvironment.ps1)
* [Get-EnvironmentVariableNames.ps1](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Get-EnvironmentVariableNames.ps1)
* [Get-EnvironmentVariable.ps1](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Get-EnvironmentVariable.ps1)

Disregard that, `[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames` to the rescue!

**Comment by ForNeVeR** [comment]
Wow, thanks for the info. It's very useful, I'll follow your advice.
