### ISSUE TITLE
ConvertTo-Json : The converted JSON string is in bad format

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/env-exporter#3]
_I'm filing that for further reference._

In PowerShell 4.0, the script will throw an error:

```
ConvertTo-Json : The converted JSON string is in bad format.
At [REDACTED]\env-exporter\Export-Env.ps1:41 char:5
+ } | ConvertTo-Json -Depth 3 | Out-File $OutPath -Encoding utf8
+     ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Collections.Hashtable:PSObject) [ConvertTo-Json], InvalidOperationException
    + FullyQualifiedErrorId : JsonStringInBadFormat,Microsoft.PowerShell.Commands.ConvertToJsonCommand
```

[That seems](https://stackoverflow.com/questions/23552000/convertto-json-throws-error-when-using-a-string-terminating-in-backslash) to be a PowerShell 4.0 bug. The workaround is to apply `-Compress` option to `ConvertTo-Json`, but its output is less manageable by version control systems then, so I won't apply the workaround.

Probably the best option is to just drop support for PowerShell 4.0 for now.

**Comment by sistoimenov** [comment]
2 years later and this issue is still open... I am looking for a fix and the best answer I get so far from my search is to use $jsonfile | ConvertTo-Json | % { [System.Text.RegularExpressions.Regex]::Unescape($_) } which is not an optimal solution...

**Comment by ForNeVeR** [comment]
@sistoimenov why is `-Compress` not an option for you?

**Comment by ForNeVeR** [comment]
Alright, we're not going to support PowerShell 4. I'll close this.
